/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vavi_uusbd_Pipe */

#ifndef _Included_vavi_uusbd_Pipe
#define _Included_vavi_uusbd_Pipe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vavi_uusbd_Pipe
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_vavi_uusbd_Pipe_close
  (JNIEnv *, jobject);

/*
 * Class:     vavi_uusbd_Pipe
 * Method:    read
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_vavi_uusbd_Pipe_read__
  (JNIEnv *, jobject);

/*
 * Class:     vavi_uusbd_Pipe
 * Method:    read
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_vavi_uusbd_Pipe_read___3BII
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     vavi_uusbd_Pipe
 * Method:    write
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_vavi_uusbd_Pipe_write__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     vavi_uusbd_Pipe
 * Method:    write
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_vavi_uusbd_Pipe_write___3BII
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     vavi_uusbd_Pipe
 * Method:    open
 * Signature: (JIIZ)V
 */
JNIEXPORT void JNICALL Java_vavi_uusbd_Pipe_open
  (JNIEnv *, jobject, jlong, jint, jint, jboolean);

/*
 * Class:     vavi_uusbd_Pipe
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_vavi_uusbd_Pipe_reset
  (JNIEnv *, jobject);

/*
 * Class:     vavi_uusbd_Pipe
 * Method:    abort
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_vavi_uusbd_Pipe_abort
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
