/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vavi_uusbd_Usb */

#ifndef _Included_vavi_uusbd_Usb
#define _Included_vavi_uusbd_Usb
#ifdef __cplusplus
extern "C" {
#endif
#undef vavi_uusbd_Usb_MASK_NO
#define vavi_uusbd_Usb_MASK_NO 0L
#undef vavi_uusbd_Usb_MASK_CLASS
#define vavi_uusbd_Usb_MASK_CLASS 1L
#undef vavi_uusbd_Usb_MASK_SUBCLASS
#define vavi_uusbd_Usb_MASK_SUBCLASS 2L
#undef vavi_uusbd_Usb_MASK_VENDOR
#define vavi_uusbd_Usb_MASK_VENDOR 4L
#undef vavi_uusbd_Usb_MASK_PRODUCT
#define vavi_uusbd_Usb_MASK_PRODUCT 8L
#undef vavi_uusbd_Usb_MASK_BCDDEVICE
#define vavi_uusbd_Usb_MASK_BCDDEVICE 16L
#undef vavi_uusbd_Usb_RECIPIENT_DEVICE
#define vavi_uusbd_Usb_RECIPIENT_DEVICE 0L
#undef vavi_uusbd_Usb_RECIPIENT_INTERFACE
#define vavi_uusbd_Usb_RECIPIENT_INTERFACE 1L
#undef vavi_uusbd_Usb_RECIPIENT_ENDPOINT
#define vavi_uusbd_Usb_RECIPIENT_ENDPOINT 2L
#undef vavi_uusbd_Usb_RECIPIENT_OTHER
#define vavi_uusbd_Usb_RECIPIENT_OTHER 3L
/*
 * Class:     vavi_uusbd_Usb
 * Method:    open
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_vavi_uusbd_Usb_open__
  (JNIEnv *, jobject);

/*
 * Class:     vavi_uusbd_Usb
 * Method:    open
 * Signature: (IIIIIB)V
 */
JNIEXPORT void JNICALL Java_vavi_uusbd_Usb_open__IIIIIB
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jbyte);

/*
 * Class:     vavi_uusbd_Usb
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_vavi_uusbd_Usb_close
  (JNIEnv *, jobject);

/*
 * Class:     vavi_uusbd_Usb
 * Method:    sendClassRequest
 * Signature: (ZIIIII[B)V
 */
JNIEXPORT void JNICALL Java_vavi_uusbd_Usb_sendClassRequest
  (JNIEnv *, jobject, jboolean, jint, jint, jint, jint, jint, jbyteArray);

/*
 * Class:     vavi_uusbd_Usb
 * Method:    sendVendorRequest
 * Signature: (ZIIIII[B)V
 */
JNIEXPORT void JNICALL Java_vavi_uusbd_Usb_sendVendorRequest
  (JNIEnv *, jobject, jboolean, jint, jint, jint, jint, jint, jbyteArray);

/*
 * Class:     vavi_uusbd_Usb
 * Method:    available
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_vavi_uusbd_Usb_available
  (JNIEnv *, jobject);

/*
 * Class:     vavi_uusbd_Usb
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_vavi_uusbd_Usb_reset
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
